#!/bin/bash
yum -y update
yum -y install httpd
echo "<html><body bgcolor=black><center><h1><font color=red>WebServer-1</h1></center></body></html>" > /var/www/html/index.html
sudo systemctl start httpd
sudo systemctl enable httpd

#!/bin/bash
yum -y update
yum -y install httpd
echo "<html><body bgcolor=black><center><h1><font color=red>WebServer-2</h1></center></body></html>" > /var/www/html/index.html
sudo systemctl start httpd
sudo systemctl enable httpd

#!/bin/bash
yum -y update
yum -y install httpd
echo "<html><body bgcolor=black><center><h1><font color=red>WebServer-3</h1></center></body></html>" > /var/www/html/index.html
sudo systemctl start httpd
sudo systemctl enable httpd